### PR TITLE
Fixes xdg-open

### PR DESCRIPTION
**Pull request by superdinmc**
This PR fixes open/browse button using code provided in https://github.com/BlackMIDIDevs/wasabi/issues/52#issuecomment-1848899553

### CODE REVIEW

**Comment by superdinmc** [comment]
It seems there's some unintended changes included in commit that I didn't notice

**Comment by arduano** [comment]
Just something to note: if you disable portals, every distro will instead use the default gnome file picker which looks horrible on things like kde. it's even worse for things like i3

We added it there to fix another issue, I'm not sure what the ideal solution here would be though. From my understanding, portals are the standard way of dealing with cross-DE file pickers

I'm not sure what the ideal solution here is.

**Comment by arduano** [comment]
Are you on gnome?

**Comment by superdinmc** [comment]
I am on KDE Plasma 5.27

**Comment by arduano** [comment]
What's the issue you're having exactly? Or are you just going through open issues on github and trying to make PRs to fix them

If it's the latter, then I apologise for not properly addressing the github issue you're fixing, that's on me

**Comment by superdinmc** [comment]
I have the same issue with them and that fix seems to work for me

**Comment by arduano** [comment]
Can you try installing `xdg-desktop-portal-kde` and then try again?

**Comment by arduano** [comment]
Just checking, did that fix your issue?

**Comment by arduano** [comment]
Closing because I presume it did, I'll address the related issue as well

**Comment by arduano** [comment]
(also I just noticed this PR completely breaks the cargo lock)

**Pull request closed without merging**
